Feature/save all
timleland/ReadLaterCE pull request #6
Opened 2020-01-03 16:22 UTC by LasyIsLazy

Then:
![readlater](https://user-images.githubusercontent.com/18400251/71734660-5a612500-2e87-11ea-9210-50f0e479373b.png)
Now:
![readlater2](https://user-images.githubusercontent.com/18400251/71734691-7369d600-2e87-11ea-8d10-e10ef352305e.png)
![readlater3](https://user-images.githubusercontent.com/18400251/71734698-7664c680-2e87-11ea-8f79-6cf1e1a82780.png)

Update:

1. Fix ellipse: long titles have difference length.
2. Support save all tabs: Save all tabs in current tab.
3. Move url to <a title="x">: When hover on title, there will be a title and url below title.

2020-01-03 16:32 UTC, LasyIsLazy commented
I hope these updates will help to this extension.

2020-01-04 01:05 UTC, timleland requested changes
Thanks for submitting this improvement!

2020-01-04 01:05 UTC, timleland commented on popup.html
> +            <button class="saveButton saveAllButton" type="button">Save All Tabs</button>
Change this to have an id="saveAllButton" so that you do not get click event for saveButton

2020-01-04 01:05 UTC, timleland commented on popup.html
>              <button class="saveButton" type="button">Save Tab</button>
Change this to have an id="saveButton" and update the javascript to target the id not the class

2020-01-04 10:03 UTC, LasyIsLazy commented
Any plan for publishing a new version?

2020-01-05 19:12 UTC, timleland requested changes

2020-01-05 19:12 UTC, timleland commented on popup.html
>              <button class="saveButton" type="button">Save Tab</button>
Add and id for "saveButton" and switch **. saveButton** to use **#saveButton**

Right now the click event will be bound to both buttons

2020-01-07 23:16 UTC, timleland approved these changes
Looks good thanks!

2020-01-07 23:16 UTC, merged